---
linux: #Группа хостов
  children: #Обозначение, что будет подгруппа хостов
    nginx: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm_1: #Имя машины 1
          ansible_host: 89.169.134.224 #Адрес машины 1
        vm_2: #Имя машины 2
          ansible_host: 89.169.158.237 #Адрес машины 2
        vm_3: #Имя машины 3
          ansible_host: 89.169.156.145 #Адрес машины 3

  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: "alexander"
    ansible_ssh_private_key_file: "/home/s10168646/.ssh/id_ed25519"
    connection_protocol: ssh #тип подключения
    ansible_become: true #Становиться ли другим пользователем после подключения
